# Importing libraries
### This section imports the Python libraries required for data manipulation, numerical computation, and visualization throughout the analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Load data
country = pd.read_csv("dim_country.csv")
date = pd.read_csv("dim_date.csv")
industry = pd.read_csv("dim_industry.csv")
skill = pd.read_csv("dim_skill_category.csv")
fact = pd.read_csv("fact_workforce_ai_index.csv")

In [5]:
country.head()

,country_id,country_code,country_name,region,development_tier,gdp_per_capita_usd,digital_infrastructure_score,ai_policy_maturity,internet_penetration_pct,stem_graduates_per_100k
0,1,US,United States,North America,Developed,33586746.94,65.5,Nascent,95.5,2270.0
1,2,GB,United Kingdom,Europe,Developed,17661249.01,79.5,Developing,84.8,1792.0
2,3,DE,Germany,Europe,Developed,42266884.66,87.3,Developing,88.7,2364.0
3,4,FR,France,Europe,Developed,21084279.93,82.4,Established,78.4,2239.0
4,5,JP,Japan,Asia-Pacific,Developed,27613361.71,69.8,Established,99.5,1723.0

In [6]:
country.shape
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country_id                    30 non-null     int64
 1   country_code                  30 non-null     object
 2   country_name                  30 non-null     object
 3   region                        30 non-null     object
 4   development_tier              30 non-null     object
 5   gdp_per_capita_usd            30 non-null     float64
 6   digital_infrastructure_score  30 non-null     float64
 7   ai_policy_maturity            30 non-null     object
 8   internet_penetration_pct      30 non-null     float64
 9   stem_graduates_per_100k       30 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 2.5+ KB

In [7]:
date.head()

,date_id,year,quarter,year_quarter_label,period_start_date,is_pandemic_period,generative_ai_era
0,1,2021,1,2021-Q1,2021-01-01,True,False
1,2,2021,2,2021-Q2,2021-04-01,True,False
2,3,2021,3,2021-Q3,2021-07-01,True,False
3,4,2021,4,2021-Q4,2021-10-01,True,False
4,5,2022,1,2022-Q1,2022-01-01,True,False

In [8]:
date.shape
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date_id             16 non-null     int64
 1   year                16 non-null     int64
 2   quarter             16 non-null     int64
 3   year_quarter_label  16 non-null     object
 4   period_start_date   16 non-null     object
 5   is_pandemic_period  16 non-null     bool
 6   generative_ai_era   16 non-null     bool
dtypes: bool(2), int64(3), object(2)
memory usage: 804.0+ bytes

In [25]:
date['period_start_date'] = pd.to_datetime(date['period_start_date'])

In [26]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date_id             16 non-null     int64
 1   year                16 non-null     int64
 2   quarter             16 non-null     int64
 3   year_quarter_label  16 non-null     object
 4   period_start_date   16 non-null     datetime64[ns]
 5   is_pandemic_period  16 non-null     bool
 6   generative_ai_era   16 non-null     bool
dtypes: bool(2), datetime64[ns](1), int64(3), object(1)
memory usage: 804.0+ bytes

In [9]:
industry.head()

,industry_id,industry_name,industry_sector,automation_susceptibility,avg_ai_investment_pct_revenue,ai_adoption_stage,global_workforce_millions,primary_ai_use_case
0,1,Information Technology,Technology,51.8,1.62,Scaling,12.1,Predictive analytics & code generation
1,2,Financial Services,Finance,53.9,6.58,Exploring,61.4,Fraud detection & algorithmic trading
2,3,Healthcare,Healthcare,45.0,1.50,Piloting,22.9,Diagnostic imaging & drug discovery
3,4,Manufacturing,Industrial,95.0,1.80,Piloting,116.1,Predictive maintenance & robotics
4,5,Retail & E-commerce,Consumer,73.6,3.30,Piloting,47.4,Demand forecasting & personalisation

In [10]:
industry. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   industry_id                    25 non-null     int64
 1   industry_name                  25 non-null     object
 2   industry_sector                25 non-null     object
 3   automation_susceptibility      25 non-null     float64
 4   avg_ai_investment_pct_revenue  25 non-null     float64
 5   ai_adoption_stage              25 non-null     object
 6   global_workforce_millions      25 non-null     float64
 7   primary_ai_use_case            25 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.7+ KB

In [15]:
skill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   skill_category_id                  8 non-null      int64
 1   skill_category_name                8 non-null      object
 2   skill_category_code                8 non-null      object
 3   ai_replaceability_score            8 non-null      float64
 4   ai_augmentation_potential          8 non-null      float64
 5   median_reskilling_duration_months  8 non-null      float64
 6   typical_education_level            8 non-null      object
 7   global_worker_share_pct            8 non-null      float64
dtypes: float64(4), int64(1), object(3)
memory usage: 644.0+ bytes

In [16]:
skill.head()

,skill_category_id,skill_category_name,skill_category_code,ai_replaceability_score,ai_augmentation_potential,median_reskilling_duration_months,typical_education_level,global_worker_share_pct
0,1,Cognitive & Analytical,COG-ANL,20.9,93.1,19.6,Bachelor's degree or higher,6.9
1,2,Manual & Physical,MAN-PHY,36.9,66.1,14.9,Vocational / on-the-job training,7.9
2,3,Creative & Design,CRE-DES,39.6,74.0,9.7,Bachelor's degree or portfolio-based,11.0
3,4,Social & Interpersonal,SOC-INT,42.1,35.3,7.0,Varies by role,11.7
4,5,Technical & Digital,TEC-DIG,50.1,50.0,9.9,Bachelor's degree or certification,18.3

In [17]:
fact.head()

,index_id,country_id,industry_id,skill_category_id,date_id,ai_adoption_rate,productivity_impact_score,displacement_risk_index,jobs_displaced_count,jobs_created_count,reskilling_investment_usd,avg_wage_change_pct,ai_tool_usage_hours_per_week,workforce_size,data_confidence_score
0,1,3,21,1,1,24.72,2.01,6.05,3739,2846,139083.86,1.74,1.5,62649,0.798
1,2,26,12,7,7,20.47,6.09,3.46,90,32,13439.86,5.39,1.4,4411,0.855
2,3,21,23,7,8,54.48,6.38,7.69,4080,2337,107635.90,-1.64,10.0,61499,0.772
3,4,20,3,5,12,48.23,2.36,4.07,311,191,226113.86,-1.65,3.0,8898,0.892
4,5,6,5,2,10,46.52,0.92,4.81,1636,890,6753.32,-1.16,8.6,39594,0.650

In [18]:
fact.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   index_id                      300 non-null    int64
 1   country_id                    300 non-null    int64
 2   industry_id                   300 non-null    int64
 3   skill_category_id             300 non-null    int64
 4   date_id                       300 non-null    int64
 5   ai_adoption_rate              300 non-null    float64
 6   productivity_impact_score     300 non-null    float64
 7   displacement_risk_index       300 non-null    float64
 8   jobs_displaced_count          300 non-null    int64
 9   jobs_created_count            300 non-null    int64
 10  reskilling_investment_usd     300 non-null    float64
 11  avg_wage_change_pct           291 non-null    float64
 12  ai_tool_usage_hours_per_week  291 non-null    float64
 13  workforce_size                300 non-null    int64
 14  data_confidence_score         300 non-null    float64
dtypes: float64(7), int64(8)
memory usage: 35.3 KB

In [20]:
fact.describe()

,index_id,country_id,industry_id,skill_category_id,date_id,ai_adoption_rate,productivity_impact_score,displacement_risk_index,jobs_displaced_count,jobs_created_count,reskilling_investment_usd,avg_wage_change_pct,ai_tool_usage_hours_per_week,workforce_size,data_confidence_score
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,3.000000e+02,291.000000,291.000000,300.000000,300.000000
mean,150.500000,15.563333,13.580000,4.560000,8.343333,30.646467,5.362067,4.264800,1955.950000,987.850000,2.055050e+05,1.228282,4.842268,77306.313333,0.796093
std,86.746758,8.538678,7.372796,2.251659,4.468259,16.508854,2.005168,2.010153,3172.323594,1468.131359,4.997389e+05,4.349630,3.601537,117405.463453,0.123924
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,0.000000,0.000000,0.000000,0.000000,4.142170e+03,-12.330000,0.000000,2606.000000,0.341000
25%,75.750000,9.000000,7.000000,3.000000,4.000000,18.540000,3.995000,2.890000,325.750000,158.000000,3.346718e+04,-1.450000,2.100000,16836.250000,0.732000
50%,150.500000,15.500000,14.000000,5.000000,8.000000,29.680000,5.500000,4.270000,888.500000,455.000000,8.445774e+04,1.100000,4.700000,36778.500000,0.814000
75%,225.250000,23.000000,20.000000,7.000000,12.000000,41.672500,6.707500,5.422500,2285.750000,1151.750000,2.029119e+05,4.050000,7.050000,88397.250000,0.888250
max,300.000000,30.000000,25.000000,8.000000,16.000000,80.330000,10.000000,10.000000,30973.000000,10585.000000,6.936681e+06,15.270000,16.100000,826001.000000,0.999000

In [21]:
fact.isnull().sum()

index_id                        0
country_id                      0
industry_id                     0
skill_category_id               0
date_id                         0
ai_adoption_rate                0
productivity_impact_score       0
displacement_risk_index         0
jobs_displaced_count            0
jobs_created_count              0
reskilling_investment_usd       0
avg_wage_change_pct             9
ai_tool_usage_hours_per_week    9
workforce_size                  0
data_confidence_score           0
dtype: int64

### Only two variables (avg_wage_change_pct and ai_tool_usage_hours_per_week) contain missing values (3% each), which aligns with the documentation. These appear to represent unavailable survey responses rather than data quality issues.

In [23]:
fact.duplicated().sum()

np.int64(0)

### No duplicated rows were found in the fact table. Therefore, no duplicate removal was required before analysis.

In [33]:
date['date_id'].duplicated().sum()

np.int64(0)

In [31]:
industry['industry_id'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: industry_id, dtype: bool

In [32]:
# Verify Primary Keys

# Before merging tables, we need to make sure the key columns don't contain duplicates

skill['skill_category_id'].duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: skill_category_id, dtype: bool

In [29]:
country['country_id'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: country_id, dtype: bool

In [39]:
len(country) == country['country_id'].nunique()

True

In [50]:
fact['country_id'].isin(country['country_id']).all()

np.True_

In [51]:
fact['date_id'].isin(date['date_id']).all()

np.True_

In [47]:
fact['skill_category_id'].isin(skill['skill_category_id']).all()

np.True_

In [48]:
fact['industry_id'].isin(industry['industry_id']).all()

np.True_

In [52]:
merged_df = (
    fact
    .merge(country, on='country_id', how ='left')
    .merge(date, on='date_id', how ='left')
    .merge(skill, on='skill_category_id', how ='left')
    .merge(industry, on='industry_id', how ='left')
)

In [53]:
merged_df.shape

(300, 44)

In [54]:
merged_df.head()

,index_id,country_id,industry_id,skill_category_id,date_id,ai_adoption_rate,productivity_impact_score,displacement_risk_index,jobs_displaced_count,jobs_created_count,...,median_reskilling_duration_months,typical_education_level,global_worker_share_pct,industry_name,industry_sector,automation_susceptibility,avg_ai_investment_pct_revenue,ai_adoption_stage,global_workforce_millions,primary_ai_use_case
0,1,3,21,1,1,24.72,2.01,6.05,3739,2846,...,19.6,Bachelor's degree or higher,6.9,Aerospace & Defence,Industrial,37.9,2.35,Scaling,14.6,Predictive maintenance & simulation
1,2,26,12,7,7,20.47,6.09,3.46,90,32,...,7.6,Bachelor's degree plus experience,24.0,Telecommunications,Technology,32.9,1.74,Mature,97.4,Network optimisation & customer service bots
2,3,21,23,7,8,54.48,6.38,7.69,4080,2337,...,7.6,Bachelor's degree plus experience,24.0,Food & Beverage,Consumer,12.1,2.51,Mature,21.0,Quality control & supply chain forecasting
3,4,20,3,5,12,48.23,2.36,4.07,311,191,...,9.9,Bachelor's degree or certification,18.3,Healthcare,Healthcare,45.0,1.50,Piloting,22.9,Diagnostic imaging & drug discovery
4,5,6,5,2,10,46.52,0.92,4.81,1636,890,...,14.9,Vocational / on-the-job training,7.9,Retail & E-commerce,Consumer,73.6,3.30,Piloting,47.4,Demand forecasting & personalisation

In [58]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 44 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   index_id                           300 non-null    int64
 1   country_id                         300 non-null    int64
 2   industry_id                        300 non-null    int64
 3   skill_category_id                  300 non-null    int64
 4   date_id                            300 non-null    int64
 5   ai_adoption_rate                   300 non-null    float64
 6   productivity_impact_score          300 non-null    float64
 7   displacement_risk_index            300 non-null    float64
 8   jobs_displaced_count               300 non-null    int64
 9   jobs_created_count                 300 non-null    int64
 10  reskilling_investment_usd          300 non-null    float64
 11  avg_wage_change_pct                291 non-null    float64
 12  ai_tool_usage_hours_per_week       291 non-null    float64
 13  workforce_size                     300 non-null    int64
 14  data_confidence_score              300 non-null    float64
 15  country_code                       300 non-null    object
 16  country_name                       300 non-null    object
 17  region                             300 non-null    object
 18  development_tier                   300 non-null    object
 19  gdp_per_capita_usd                 300 non-null    float64
 20  digital_infrastructure_score       300 non-null    float64
 21  ai_policy_maturity                 300 non-null    object
 22  internet_penetration_pct           300 non-null    float64
 23  stem_graduates_per_100k            300 non-null    float64
 24  year                               300 non-null    int64
 25  quarter                            300 non-null    int64
 26  year_quarter_label                 300 non-null    object
 27  period_start_date                  300 non-null    datetime64[ns]
 28  is_pandemic_period                 300 non-null    bool
 29  generative_ai_era                  300 non-null    bool
 30  skill_category_name                300 non-null    object
 31  skill_category_code                300 non-null    object
 32  ai_replaceability_score            300 non-null    float64
 33  ai_augmentation_potential          300 non-null    float64
 34  median_reskilling_duration_months  300 non-null    float64
 35  typical_education_level            300 non-null    object
 36  global_worker_share_pct            300 non-null    float64
 37  industry_name                      300 non-null    object
 38  industry_sector                    300 non-null    object
 39  automation_susceptibility          300 non-null    float64
 40  avg_ai_investment_pct_revenue      300 non-null    float64
 41  ai_adoption_stage                  300 non-null    object
 42  global_workforce_millions          300 non-null    float64
 43  primary_ai_use_case                300 non-null    object
dtypes: bool(2), datetime64[ns](1), float64(18), int64(10), object(13)
memory usage: 99.2+ KB

In [68]:
## How has AI adoption changed quarter over quarter since the Generative AI era began in Q4 2022?
quarterly_ai = (
    merged_df
    .groupby(['year_quarter_label'])['ai_adoption_rate']
    .mean()
    .reset_index()
)
quarterly_ai

   year_quarter_label  ai_adoption_rate
0             2021-Q1         19.150000
1             2021-Q2         22.351579
2             2021-Q3         21.202174
3             2021-Q4         20.195455
4             2022-Q1         16.682000
5             2022-Q2         19.594000
6             2022-Q3         22.481176
7             2022-Q4         40.234583
8             2023-Q1         34.189231
9             2023-Q2         38.756538
10            2023-Q3         38.152917
11            2023-Q4         38.644118
12            2024-Q1         45.701667
13            2024-Q2         37.347500
14            2024-Q3         33.281500
15            2024-Q4         39.930667

In [64]:
## The percentage increase from 2022-Q3 to 2022-Q4.

old = 22.481176
new = 40.234583

increase = ((new - old) / old) * 100
print(increase)

78.97009925103562

In [65]:
# Is the rate of job displacement accelerating or stabilizing across 2023–2024?
quarterly_job_displacement = (
    merged_df
    .groupby(['year_quarter_label'])['jobs_displaced_count']
    .mean()
    .reset_index()
)
quarterly_job_displacement

   year_quarter_label  jobs_displaced_count
0             2021-Q1           2641.933333
1             2021-Q2           1424.210526
2             2021-Q3           1547.739130
3             2021-Q4            720.363636
4             2022-Q1           2517.533333
5             2022-Q2           1454.700000
6             2022-Q3           1150.235294
7             2022-Q4           3101.750000
8             2023-Q1           3239.615385
9             2023-Q2           3606.500000
10            2023-Q3           2010.166667
11            2023-Q4            722.470588
12            2024-Q1           1940.388889
13            2024-Q2           1442.083333
14            2024-Q3           1804.350000
15            2024-Q4           1537.866667

In [69]:
# how many records each quarter contains.
merged_df.groupby('year_quarter_label').size()

year_quarter_label
2021-Q1    15
2021-Q2    19
2021-Q3    23
2021-Q4    22
2022-Q1    15
2022-Q2    20
2022-Q3    17
2022-Q4    24
2023-Q1    13
2023-Q2    26
2023-Q3    24
2023-Q4    17
2024-Q1    18
2024-Q2    12
2024-Q3    20
2024-Q4    15
dtype: int64

In [78]:
# Which quarters show the steepest rise in ai_tool_usage_hours_per_week?
# Calculate the average AI usage per quarter
quarterly_usage = (
    merged_df
    .groupby('year_quarter_label')['ai_tool_usage_hours_per_week']
    .mean()
    .reset_index()
)
    
quarterly_usage['Rise'] = quarterly_usage['ai_tool_usage_hours_per_week'].diff()

# Return only the quarter with the steepest rise
steepest_rise = quarterly_usage.loc[quarterly_usage['Rise'].idxmax()]

print(steepest_rise)

year_quarter_label               2022-Q4
ai_tool_usage_hours_per_week    6.095833
Rise                            3.442892
Name: 7, dtype: object

In [80]:
# Is job creation offsetting job displacement?
quarterly_jobs = (
    merged_df
    .groupby('year_quarter_label')[['jobs_displaced_count', 'jobs_created_count']]
    .mean()
    .reset_index()
)

In [81]:
quarterly_jobs['job_replacement_ratio'] = (
    quarterly_jobs['jobs_created_count']
    / quarterly_jobs['jobs_displaced_count']
)

quarterly_jobs

,year_quarter_label,jobs_displaced_count,jobs_created_count,job_replacement_ratio
0,2021-Q1,2641.933333,1395.666667,0.528275
1,2021-Q2,1424.210526,643.578947,0.451885
2,2021-Q3,1547.739130,878.130435,0.567363
3,2021-Q4,720.363636,461.636364,0.640838
4,2022-Q1,2517.533333,1450.600000,0.576199
5,2022-Q2,1454.700000,676.950000,0.465354
6,2022-Q3,1150.235294,591.470588,0.514217
7,2022-Q4,3101.750000,1189.000000,0.383332
8,2023-Q1,3239.615385,1948.153846,0.601353
9,2023-Q2,3606.500000,1565.423077,0.434056
10,2023-Q3,2010.166667,1052.125000,0.523402
11,2023-Q4,722.470588,437.117647,0.605032
12,2024-Q1,1940.388889,973.111111,0.501503
13,2024-Q2,1442.083333,859.666667,0.596128
14,2024-Q3,1804.350000,961.200000,0.532713
15,2024-Q4,1537.866667,879.000000,0.571571

In [85]:
# Which industries combine high automation susceptibility with low average AI investment (% revenue), suggesting they are under-prepared?
industry_preparedness = (
    merged_df
    .groupby('industry_name')[[
        'automation_susceptibility',
        'avg_ai_investment_pct_revenue'
    ]]
    .mean()
    .reset_index()
)
industry_preparedness

,industry_name,automation_susceptibility,avg_ai_investment_pct_revenue
0,Aerospace & Defence,37.9,2.35
1,Agriculture,58.7,1.47
2,Automotive,50.5,3.07
3,Construction,89.5,2.48
4,Education,29.4,2.96
5,Energy & Utilities,46.8,4.73
6,Financial Services,53.9,6.58
7,Food & Beverage,12.1,2.51
8,Government & Public Sector,54.9,2.50
9,Healthcare,45.0,1.50
10,Hospitality & Tourism,38.1,1.48
11,Information Technology,51.8,1.62
12,Insurance,64.8,2.13
13,Legal Services,56.8,3.75
14,Manufacturing,95.0,1.80
15,Marketing & Advertising,19.8,1.31
16,Media & Entertainment,52.6,3.14
17,Mining & Resources,61.3,4.97
18,Pharmaceuticals,65.8,5.31
19,Professional Services,56.8,3.05
20,Public Health,95.0,2.09
21,Real Estate,73.3,1.40
22,Retail & E-commerce,73.6,3.30
23,Telecommunications,32.9,1.74
24,Transportation & Logistics,41.9,3.40

In [86]:
industry_preparedness.sort_values(
    by=['automation_susceptibility',
        'avg_ai_investment_pct_revenue'],
    ascending=[False, True]
)

,industry_name,automation_susceptibility,avg_ai_investment_pct_revenue
14,Manufacturing,95.0,1.80
20,Public Health,95.0,2.09
3,Construction,89.5,2.48
22,Retail & E-commerce,73.6,3.30
21,Real Estate,73.3,1.40
18,Pharmaceuticals,65.8,5.31
12,Insurance,64.8,2.13
17,Mining & Resources,61.3,4.97
1,Agriculture,58.7,1.47
19,Professional Services,56.8,3.05
13,Legal Services,56.8,3.75
8,Government & Public Sector,54.9,2.50
6,Financial Services,53.9,6.58
16,Media & Entertainment,52.6,3.14
11,Information Technology,51.8,1.62
2,Automotive,50.5,3.07
5,Energy & Utilities,46.8,4.73
9,Healthcare,45.0,1.50
24,Transportation & Logistics,41.9,3.40
10,Hospitality & Tourism,38.1,1.48
0,Aerospace & Defence,37.9,2.35
23,Telecommunications,32.9,1.74
4,Education,29.4,2.96
15,Marketing & Advertising,19.8,1.31
7,Food & Beverage,12.1,2.51

In [88]:
# Which skill categories show the largest gap between ai_replaceability_score and median_reskilling_duration_months?
skill_gap = (
    merged_df
    .groupby('skill_category_name')[[
        'ai_replaceability_score',
        'median_reskilling_duration_months'
    ]]
    .mean()
    .reset_index()
)
skill_gap['reskilling_gap'] = (
    skill_gap['ai_replaceability_score']
    - skill_gap['median_reskilling_duration_months']
)

largest_gap = skill_gap.loc[skill_gap['reskilling_gap'].idxmax()]
print(largest_gap)

skill_category_name                  Manual Skilled Trades
ai_replaceability_score                               79.6
median_reskilling_duration_months                      4.9
reskilling_gap                                        74.7
Name: 5, dtype: object

In [90]:
# Are creative and interpersonal skill categories more resilient to displacement than administrative or manual ones?
skill_gap.sort_values(
    by='reskilling_gap',
    ascending=False
)

,skill_category_name,ai_replaceability_score,median_reskilling_duration_months,reskilling_gap
5,Manual Skilled Trades,79.6,4.9,74.7
0,Administrative & Clerical,48.4,8.2,40.2
7,Technical & Digital,50.1,9.9,40.2
6,Social & Interpersonal,42.1,7.0,35.1
2,Creative & Design,39.6,9.7,29.9
4,Manual & Physical,36.9,14.9,22.0
3,Managerial & Strategic,29.1,7.6,21.5
1,Cognitive & Analytical,20.9,19.6,1.3

In [91]:
# How does displacement_risk_index correlate with digital_infrastructure_score and stem_graduates_per_100k by country?
country_analysis = (
    merged_df
    .groupby('country_name')[[
        'displacement_risk_index',
        'digital_infrastructure_score',
        'stem_graduates_per_100k'
    ]]
    .mean()
    .reset_index()
)

country_analysis.head()

,country_name,displacement_risk_index,digital_infrastructure_score,stem_graduates_per_100k
0,Australia,3.942500,88.5,2139.0
1,Brazil,4.111429,50.6,688.0
2,Canada,3.945385,84.5,1916.0
3,China,6.105000,58.4,1306.0
4,Egypt,4.178182,69.6,780.0

In [92]:
# Calculate the Correlations
country_analysis[[
    'displacement_risk_index',
    'digital_infrastructure_score',
    'stem_graduates_per_100k'
]].corr()

,displacement_risk_index,digital_infrastructure_score,stem_graduates_per_100k
displacement_risk_index,1.000000,-0.192209,-0.320223
digital_infrastructure_score,-0.192209,1.000000,0.631102
stem_graduates_per_100k,-0.320223,0.631102,1.000000

In [95]:
# Do countries with more mature ai_policy_maturity show better job creation-to-displacement ratios?
merged_df['job_replacement_ratio'] = (
    merged_df['jobs_created_count']
    / merged_df['jobs_displaced_count']
)

In [94]:
# Create the Ratio
merged_df['ai_policy_maturity'].unique()

array(['Developing', 'Advanced', 'Established', 'Nascent'], dtype=object)

In [96]:
## Group by Policy Maturity
policy_analysis = (
    merged_df
    .groupby('ai_policy_maturity')['job_replacement_ratio']
    .mean()
    .reset_index()
)

policy_analysis

  ai_policy_maturity  job_replacement_ratio
0           Advanced               0.601757
1         Developing               0.545607
2        Established               0.513275
3            Nascent               0.555529

In [98]:
# Which regions show the widest gap between developed and emerging economy adoption rates?
regional_gap = (
    merged_df
    .groupby(['region', 'development_tier'])['ai_adoption_rate']
    .mean()
    .unstack()          # Turns Developed and Emerging into separate columns
)

regional_gap['adoption_gap'] = (
    regional_gap['Developed'] - regional_gap['Emerging']
)

regional_gap = regional_gap.sort_values(
    by='adoption_gap',
    ascending=False
)

regional_gap

development_tier  Developed   Emerging  adoption_gap
region
Asia-Pacific      31.241944  30.142830      1.099114
Europe            31.849432  31.201538      0.647893
Middle East       29.830000  30.614091     -0.784091
Africa                  NaN  31.962963           NaN
Latin America           NaN  26.432353           NaN
North America     28.367917        NaN           NaN

In [99]:
merged_df.groupby(['region', 'development_tier'])['country_name'].nunique()

region         development_tier
Africa         Emerging            2
Asia-Pacific   Developed           4
               Emerging            6
Europe         Developed           9
               Emerging            1
Latin America  Emerging            2
Middle East    Developed           2
               Emerging            2
North America  Developed           2
Name: country_name, dtype: int64

In [100]:
# Is reskilling_investment_usd keeping pace with jobs_displaced_count at an industry level?
industry_reskilling = (
    merged_df
    .groupby('industry_name')[[
        'jobs_displaced_count',
        'reskilling_investment_usd'
    ]]
    .mean()
    .reset_index()
)

industry_reskilling

,industry_name,jobs_displaced_count,reskilling_investment_usd
0,Aerospace & Defence,1740.769231,2.225323e+05
1,Agriculture,1972.000000,1.136280e+05
2,Automotive,2269.555556,2.050855e+05
3,Construction,1600.375000,3.855035e+05
4,Education,2194.928571,1.216595e+05
5,Energy & Utilities,960.538462,1.653022e+05
6,Financial Services,1801.250000,1.143658e+05
7,Food & Beverage,3484.111111,1.921020e+05
8,Government & Public Sector,1549.363636,1.376842e+05
9,Healthcare,2366.000000,2.706888e+05
10,Hospitality & Tourism,2267.642857,2.624374e+05
11,Information Technology,2142.200000,1.010508e+06
12,Insurance,1438.500000,2.081441e+05
13,Legal Services,1268.000000,1.082109e+05
14,Manufacturing,3279.777778,1.097697e+05
15,Marketing & Advertising,419.571429,1.737277e+05
16,Media & Entertainment,4093.200000,4.632525e+04
17,Mining & Resources,1183.000000,1.046908e+05
18,Pharmaceuticals,1377.800000,4.275500e+05
19,Professional Services,2640.272727,1.031125e+05
20,Public Health,1735.000000,2.127731e+05
21,Real Estate,1670.750000,1.238204e+05
22,Retail & E-commerce,2151.739130,1.555813e+05
23,Telecommunications,909.166667,1.534728e+05
24,Transportation & Logistics,1666.100000,1.102766e+05

In [101]:
# Investment per displaced worker
industry_reskilling['investment_per_displaced_worker'] = (
    industry_reskilling['reskilling_investment_usd']
    / industry_reskilling['jobs_displaced_count']
)

industry_reskilling.sort_values(
    by='investment_per_displaced_worker'
)

,industry_name,jobs_displaced_count,reskilling_investment_usd,investment_per_displaced_worker
16,Media & Entertainment,4093.200000,4.632525e+04,11.317613
14,Manufacturing,3279.777778,1.097697e+05,33.468637
19,Professional Services,2640.272727,1.031125e+05,39.053727
7,Food & Beverage,3484.111111,1.921020e+05,55.136590
4,Education,2194.928571,1.216595e+05,55.427556
1,Agriculture,1972.000000,1.136280e+05,57.620693
6,Financial Services,1801.250000,1.143658e+05,63.492459
24,Transportation & Logistics,1666.100000,1.102766e+05,66.188480
22,Retail & E-commerce,2151.739130,1.555813e+05,72.304913
21,Real Estate,1670.750000,1.238204e+05,74.110675
13,Legal Services,1268.000000,1.082109e+05,85.339838
17,Mining & Resources,1183.000000,1.046908e+05,88.496027
8,Government & Public Sector,1549.363636,1.376842e+05,88.864976
2,Automotive,2269.555556,2.050855e+05,90.363740
9,Healthcare,2366.000000,2.706888e+05,114.407787
10,Hospitality & Tourism,2267.642857,2.624374e+05,115.731380
20,Public Health,1735.000000,2.127731e+05,122.635767
0,Aerospace & Defence,1740.769231,2.225323e+05,127.835605
12,Insurance,1438.500000,2.081441e+05,144.695229
23,Telecommunications,909.166667,1.534728e+05,168.805984
5,Energy & Utilities,960.538462,1.653022e+05,172.093221
3,Construction,1600.375000,3.855035e+05,240.883247
18,Pharmaceuticals,1377.800000,4.275500e+05,310.313568
15,Marketing & Advertising,419.571429,1.737277e+05,414.059997
11,Information Technology,2142.200000,1.010508e+06,471.715226

In [102]:
# Which country–industry combination has the largest shortfall between displacement risk and reskilling spending?
country_industry = (
    merged_df
    .groupby(['country_name', 'industry_name'])[
        ['displacement_risk_index', 'reskilling_investment_usd']
    ]
    .mean()
    .reset_index()
)

# Convert investment to millions (optional, makes the numbers easier to read)
country_industry['investment_million'] = (
    country_industry['reskilling_investment_usd'] / 1_000_000
)

country_industry['shortfall_score'] = (
    country_industry['displacement_risk_index']
    / country_industry['investment_million']
)

country_industry = country_industry.sort_values(
    by='shortfall_score',
    ascending=False
)

country_industry.head(10)

,country_name,industry_name,displacement_risk_index,reskilling_investment_usd,investment_million,shortfall_score
66,Indonesia,Aerospace & Defence,5.080,4899.39,0.004899,1036.863773
71,Indonesia,Media & Entertainment,5.530,6374.14,0.006374,867.568017
52,Germany,Manufacturing,4.020,4748.43,0.004748,846.595612
31,China,Retail & E-commerce,4.810,6753.32,0.006753,712.242275
131,Philippines,Aerospace & Defence,4.500,6973.04,0.006973,645.342634
77,Ireland,Manufacturing,5.080,8125.88,0.008126,625.163059
164,Singapore,Media & Entertainment,5.370,8815.66,0.008816,609.143275
68,Indonesia,Food & Beverage,5.580,9999.83,0.010000,558.009486
210,United Arab Emirates,Media & Entertainment,6.120,12248.36,0.012248,499.658730
32,Egypt,Energy & Utilities,5.715,11471.81,0.011472,498.177707